Name: Syed Sameer Rizvi
------------------------------
AICP Internship Task Week 1
-----------------------

In [1]:
import numpy as np

Q1) Write a NumPy program to create an array of all even integers from 30 to 70
--------------------------------------------------------------

In [31]:
arr = np.arange(30,71,2)
print(arr)

[30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


Q2) Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution.
---------------------------------------


In [32]:
arr = np.random.randn(15)
print(arr)

[-0.45790735 -0.61862214  0.03978283 -0.48119928 -1.08560589 -1.10941197
  0.86560821 -0.44856884 -0.60909207  0.12758204  0.11431041 -0.06851046
 -0.01649015 -0.48769206  1.21927233]


Q3) How to compute the cross-product of two matrices in NumPy?
-------------------------------------------------------

In [33]:
mat_A = np.array([[1,2,3],[4,5,6],[7,8,9]])
mat_B = np.array([[1,4,5],[6,3,2],[10,2,3]])
mat_C = np.cross(mat_A,mat_B)
print(mat_C)

[[ -2  -2   2]
 [ -8  28 -18]
 [  6  69 -66]]


Q4) How to compute the determinant of an array using NumPy?
-------------------------------------------------

In [34]:
arr = np.array([[1,2],[4,5]])
det_arr = np.linalg.det(arr)
print(round(det_arr,2))

-3.0


Q5) How to create a 3x3x3 array with random values using NumPy?
----------------------------------------


In [35]:
dimensions = (3,3,3)
mat_A = np.random.randint(1,15,size=dimensions)
print(mat_A)

[[[14 14  5]
  [14  7  9]
  [ 9 14  8]]

 [[ 1  2 13]
  [ 4  8  8]
  [10  6 11]]

 [[ 2 12  3]
  [12  8  5]
  [ 6  8  6]]]


Q6) How to create a 5x5 array with random values and find the minimum and maximum values using NumPy?
---------------------------------------------

In [36]:
dimensions = (5,5)
mat_A = np.random.randint(1,25,size=dimensions)
print(mat_A)

result_1 = np.min(mat_A)
print("The minimun value is: ",result_1)

result_2 = np.max(mat_A)
print("The maximum value is: ",result_2)

[[13 15 11  5  1]
 [ 9 13 15 13 12]
 [14  5 21 15 17]
 [ 1 16  5  5 20]
 [ 9  8 14 21 18]]
The minimun value is:  1
The maximum value is:  21


Q7) How to compute the mean, standard deviation, and variance of a given array along the second axis in NumPy?
---------------------------------------------



In [37]:
arr = np.array([[1,4,5],[6,3,2],[10,2,3]])
mean_arr = np.mean(arr,axis=1)
var_arr = np.var(arr,axis=1)
std_arr = np.std(arr,axis=1)

print("The mean is: ",mean_arr)
print("The variance is: ",var_arr)
print("The standard deviation is: ",std_arr)

The mean is:  [3.33333333 3.66666667 5.        ]
The variance is:  [ 2.88888889  2.88888889 12.66666667]
The standard deviation is:  [1.69967317 1.69967317 3.55902608]
